### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by tinamore** [samueleaton/autossh#3]
Hi
I have error when run example:

file:ssh.js:
```
autossh({
  host: '111.22.333.444',
  username: 'root',
  localPort: 64444,
  remotePort: 5432
})
.on('error', err => {
  console.error('ERROR: ', err);
})
.on('connect', connection => {
  console.log('Tunnel established on port ' + connection.localPort);
  console.log('pid: ' + connection.pid);
});
```
Show error:

```
/home/node/ssh.js:7
.on('error', err => {
                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

how to fix this error ?
Thanks

**Comment by samueleaton** [comment]
it looks like your version of node doesn't support [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). Do `function (err) {}` instead of `err => {}`. which version of node are you using?

**Comment by tinamore** [comment]
Ok. i fixed and now code run good. Thanks.

```
const autossh = require('autossh');
autossh({
 ...
})
.on('error',function(err){
  console.error('ERROR: ', err);
})
.on('connect',function(connection){
  console.log('Tunnel established on port ' + connection.localPort);
  console.log('pid: ' + connection.pid);
});
```
